print("---------------------------------------")
print(" Tugas 1 SISOP Kelas-A")
print("---------------------------------------")
print("Nama : Denisa septalian alhamda")
print("NPM  : 21083010113")
print("---------------------------------------")
print("Notes")
print("mantab sekali")
print("Halo dunia!")
print("ini adalah skrip bash pertamaku dilinux")
